// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: issues.sql

package repository

import (
	"context"
	"database/sql"
)

const addTestIssues = `-- name: AddTestIssues :execresult
INSERT INTO issues(id, url, title, closed, number, repository) VALUES
('ISSUE_1', 'http://example.com/repo1/issue/1', 'First Issue', 1, 1, 'REPO_1'),
('ISSUE_2', 'http://example.com/repo1/issue/2', 'Second Issue', 0, 2, 'REPO_1'),
('ISSUE_3', 'http://example.com/repo1/issue/3', 'Third Issue', 0, 3, 'REPO_1')
`

func (q *Queries) AddTestIssues(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, addTestIssues)
}
